CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_PERIPHERAL=y

# Dongle Display（右だけ！）
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY=y
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
CONFIG_ZMK_DONGLE_DISPLAY_MAC_MODIFIERS=n

# I2C
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

# Cirque Trackpad
CONFIG_ZMK_POINTING=y
CONFIG_INPUT_CIRQUE=y

# Battery
CONFIG_BT_BAS=y
CONFIG_ZMK_BATTERY_REPORTING=y
